apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-manager
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Take-st/argocd-k8s-practice
    targetRevision: HEAD
    path: deploy/apps
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
